modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/Unbreakables/issues"

[[mods]]
modId="unbreakables"
version="${mod_version}"
displayName="Unbreakables"
displayURL="https://mods.twelveiterations.com/mc/unbreakables"
logoFile="unbreakables-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Configure blocks to be unbreakable under certain conditions. With support for Waystones.
'''

[[dependencies.unbreakables]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.unbreakables]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.unbreakables]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
