modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="unbreakables"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="unbreakables.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "unbreakables.mixins.json"
[[mixins]]
config = "unbreakables.forge.mixins.json"
[[dependencies.unbreakables]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.unbreakables]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.unbreakables]]
modId="balm"
mandatory=true
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.unbreakables]]
modId="shogi"
mandatory=true
versionRange="[${shogi_version},)"
ordering="NONE"
side="BOTH"